version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: osmos
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/osmos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
