apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvbt-k8s
spec:
  selector:
    matchLabels:
      app: dvbt-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: dvbt-k8s
    spec:
      containers:
        - name: dvbt-server
          image: 423414/markult:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000