apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvbt-minio
spec:
  selector:
    matchLabels:
      app: dvbt-minio
  template:
    metadata:
      labels:
        app: dvbt-minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              value: b3S56Y2wHvn7
            - name: MINIO_SECRET_KEY
              value: A9DFm3Ucof7e
            - name: MINIO_ROOT_USER
              value: minio_user
            - name: MINIO_ROOT_PASSWORD
              value: b3S56Y2wHvn7
---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: dvbt-minio
  ports:
    - protocol: TCP
      name: api
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: console
      port: 9001
      targetPort: 9001
