apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvbt-redis
spec:
  selector:
    matchLabels:
      app: dvbt-redis
  template:
    metadata:
      labels:
        app: dvbt-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: pass
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: dvbt-redis
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 6379